function [PHASE_STATS] = BROADNESS_PhaseSpaceStatistics(RQA_BROADNESS, varargin)
%%
% ========================================================================
%  BROADBAND BRAIN NETWORK ESTIMATION VIA SOURCE SEPARATION (BROADNESS) TOOLBOX
%  PHASE-SPACE METRICS AND STATISTICS
% ========================================================================
%
%  Please cite the first BROADNESS paper:
%  Bonetti, L., Fernandez-Rubio, G., Andersen, M. H., Malvaso, C., Carlomagno,
%  F., Testa, C., Vuust, P, Kringelbach, M.L., & Rosso, M. (2025). Advanced Science.
%  BROAD-NESS Uncovers Dual-Stream Mechanisms Underlying Predictive Coding in Auditory Memory Networks.
%  https://doi.org/10.1002/advs.202507878
%
% ========================================================================
%
%  This function computes descriptive and inferential measures directly
%  from the phase-space coordinates generated by BROADNESS_PhaseSpace_RQA.
%
%  Specifically, it:
%   - Computes Euclidean distances between condition-average trajectories
%   - Computes participant-level dispersion, speed, acceleration,
%     baseline displacement, and cumulative/total path length
%   - Tests multivariate trajectory separation using Hotelling's T-squared
%   - Tests scalar metrics with parametric and/or rank-based tests
%   - Supports paired condition comparisons, independent group comparisons,
%     group-by-condition interactions, and repeated/mixed omnibus ANOVA
%   - Applies Benjamini-Hochberg FDR correction across time and comparisons
%
% ------------------------------------------------------------------------
%  INPUT ARGUMENTS:
% ------------------------------------------------------------------------
%  - RQA_BROADNESS                    : Structure outputted by
%                                       BROADNESS_PhaseSpace_RQA, containing:
%      - .PhaseSpace.Time             : Analysed time points in seconds
%      - .PhaseSpace.PCs              : Components used as phase-space dimensions
%      - .PhaseSpace.ParticipantCoordinates
%                                     : Cell array (conditions x participants)
%
%  - Optional arguments (name-value pairs):
%      - 'conditionindices'           : Conditions to analyse (default: all)
%      - 'conditionnames'             : One label per selected condition
%      - 'groupindices'               : Cell array of participant-index vectors,
%                                       or one numeric group label per participant
%      - 'groupnames'                 : One label per specified group
%      - 'statistics'                 : 'on' or 'off' (default: 'on')
%      - 'testtype'                   : Pairwise scalar-metric tests:
%                                       'parametric', 'nonparametric', or
%                                       'both' (default: 'parametric')
%      - 'pairwise'                   : 'on' or 'off' (default: 'on')
%      - 'omnibus'                    : 'on' or 'off' (default: 'on')
%      - 'alpha'                      : Statistical alpha (default: 0.05)
%      - 'fdr'                        : 'on' or 'off' (default: 'on')
%      - 'baseline'                   : [start end] in seconds. By default,
%                                       all available samples at or before zero
%                                       are used, or the first sample if none
%      - 'smoothingsamples'           : Moving-average width applied before
%                                       derivatives (default: 1, no smoothing)
%      - 'testmetrics'                : Scalar metrics submitted to statistics
%                                       (default: all metrics)
%
% ------------------------------------------------------------------------
%  OUTPUT:
% ------------------------------------------------------------------------
%  - PHASE_STATS                      : Structure containing:
%      - .Metrics                     : Participant-level phase-space metrics
%      - .Descriptive                 : Condition means and Euclidean separation
%      - .Tests.PhaseSpace            : Hotelling tests of trajectory separation
%      - .Tests.Metrics               : Pairwise and omnibus scalar-metric tests
%      - .Settings                    : Analysis settings and labels
%
%  No files are written to disk by this function.
%
% ------------------------------------------------------------------------
%  NOTES:
% ------------------------------------------------------------------------
%  - Condition comparisons must contain the same participants in the same
%    order and are tested as paired observations.
%  - Group comparisons are independent and use Welch's t-test by default.
%  - Dispersion is the distance to the centroid pooled across selected
%    conditions and all other included participants. For singleton data,
%    the participant's across-condition centroid is used descriptively.
%  - Hotelling tests are most appropriate when the number of participants
%    is larger than the number of selected phase-space dimensions.
%  - FDR is applied separately to each output family (phase-space condition,
%    group and interaction comparisons, and each scalar-metric comparison
%    category). Omnibus ANOVA effects are corrected across time separately.
%  - The omnibus analysis is parametric. The 'nonparametric' option applies
%    to pairwise scalar-metric comparisons.
%  - Greenhouse-Geisser correction is applied to omnibus condition and
%    interaction effects when more than two conditions are analysed.
%  - Exact zeros retained in the phase-space coordinates remain part of all
%    computations performed by this function.
%
% ========================================================================
%  AUTHORS:
%  Leonardo Bonetti, Mathias Houe Andersen, Mattia Rosso
%  leonardo.bonetti@clin.au.dk; leonardo.bonetti@psych.ox.ac.uk
%  mathias.houe.andersen@regionh.dk
%  mattia.rosso@clin.au.dk
%  Center for Music in the Brain, Aarhus University
%  Centre for Eudaimonia and Human Flourishing, Linacre College, University of Oxford
%  Aarhus (DK), Oxford (UK)
%
% ========================================================================

%% ----------------------------- Parse inputs -----------------------------

disp('Checking inputs')

opts = struct( ...
    'conditionindices', [], ...
    'conditionnames', {{}}, ...
    'groupindices', [], ...
    'groupnames', {{}}, ...
    'statistics', 'on', ...
    'testtype', 'parametric', ...
    'pairwise', 'on', ...
    'omnibus', 'on', ...
    'alpha', 0.05, ...
    'fdr', 'on', ...
    'baseline', [], ...
    'smoothingsamples', 1, ...
    'testmetrics', {{'Dispersion','Speed','Acceleration', ...
                     'BaselineDisplacement','CumulativePathLength','TotalPathLength'}});
opts = parse_name_value_pairs(opts, varargin{:});

if ~isfield(RQA_BROADNESS, 'PhaseSpace')
    error('Invalid input: RQA_BROADNESS.PhaseSpace is required.');
end
if ~isfield(RQA_BROADNESS.PhaseSpace, 'Time') || ...
        ~isfield(RQA_BROADNESS.PhaseSpace, 'PCs') || ...
        ~isfield(RQA_BROADNESS.PhaseSpace, 'ParticipantCoordinates')
    error(['Invalid input: the PhaseSpace structure must contain "Time", ' ...
           '"PCs", and "ParticipantCoordinates".']);
end

validate_on_off(opts.statistics, 'statistics');
validate_on_off(opts.pairwise, 'pairwise');
validate_on_off(opts.omnibus, 'omnibus');
validate_on_off(opts.fdr, 'fdr');

validTestTypes = {'parametric','nonparametric','both'};
if ~(ischar(opts.testtype) || (isstring(opts.testtype) && isscalar(opts.testtype))) || ...
        ~any(strcmpi(char(opts.testtype), validTestTypes))
    error('"testtype" must be ''parametric'', ''nonparametric'', or ''both''.');
end
testType = lower(char(opts.testtype));

if ~isnumeric(opts.alpha) || ~isscalar(opts.alpha) || ...
        ~isfinite(opts.alpha) || opts.alpha <= 0 || opts.alpha >= 1
    error('"alpha" must be a numeric scalar between 0 and 1.');
end
if ~isnumeric(opts.smoothingsamples) || ~isscalar(opts.smoothingsamples) || ...
        ~isfinite(opts.smoothingsamples) || opts.smoothingsamples < 1 || ...
        fix(opts.smoothingsamples) ~= opts.smoothingsamples
    error('"smoothingsamples" must be a positive integer.');
end

time = RQA_BROADNESS.PhaseSpace.Time(:);
PCs = RQA_BROADNESS.PhaseSpace.PCs(:)';
participantCoordinates = RQA_BROADNESS.PhaseSpace.ParticipantCoordinates;

if ~iscell(participantCoordinates) || isempty(participantCoordinates)
    error('"ParticipantCoordinates" must be a non-empty cell array.');
end
if numel(time) < 3 || any(~isfinite(time)) || any(diff(time) <= 0)
    error('PhaseSpace.Time must contain at least three finite, increasing samples.');
end

nConditionsOriginal = size(participantCoordinates, 1);
nParticipants = size(participantCoordinates, 2);

if isempty(opts.conditionindices)
    conditionIndices = 1:nConditionsOriginal;
else
    conditionIndices = opts.conditionindices(:)';
    if ~isnumeric(conditionIndices) || isempty(conditionIndices) || ...
            any(~isfinite(conditionIndices)) || any(conditionIndices < 1) || ...
            any(conditionIndices > nConditionsOriginal) || ...
            any(fix(conditionIndices) ~= conditionIndices) || ...
            length(unique(conditionIndices)) ~= length(conditionIndices)
        error('"conditionindices" must contain unique valid condition indices.');
    end
end

participantCoordinates = participantCoordinates(conditionIndices, :);
nConditions = length(conditionIndices);
conditionNames = normalize_names(opts.conditionnames, nConditions, 'Condition');
[groupMembers, groupNames, groupLabels] = normalize_groups( ...
    opts.groupindices, opts.groupnames, nParticipants);
participantsIncluded = unique([groupMembers{:}], 'stable');

%% -------------------- Prepare phase-space trajectories -----------------

disp('Preparing participant phase-space trajectories')

firstTrajectory = participantCoordinates{1,1};
if ~isnumeric(firstTrajectory) || size(firstTrajectory,1) ~= length(time)
    error('Each participant trajectory must be a numeric time x components matrix.');
end
nDimensions = size(firstTrajectory,2);
if nDimensions ~= length(PCs)
    error('The number of trajectory dimensions must match PhaseSpace.PCs.');
end

trajectories = nan(length(time), nDimensions, nConditions, nParticipants);
for cond = 1:nConditions
    for part = 1:nParticipants
        currentTrajectory = participantCoordinates{cond,part};
        if ~isnumeric(currentTrajectory) || ~isequal(size(currentTrajectory), size(firstTrajectory))
            error('All participant trajectories must have the same time x components dimensions.');
        end
        trajectories(:,:,cond,part) = currentTrajectory;
    end
end

if opts.smoothingsamples > 1
    disp(['Smoothing trajectories with a ' num2str(opts.smoothingsamples) '-sample moving average'])
    trajectories = movmean(trajectories, opts.smoothingsamples, 1, 'Endpoints', 'shrink');
end

%% ---------------------- Compute descriptive metrics --------------------

disp('Computing phase-space metrics')

nTime = length(time);
meanCoordinates = mean(trajectories(:,:,:,participantsIncluded), 4, 'omitnan');

velocity = nan(size(trajectories));
accelerationVector = nan(size(trajectories));
speed = nan(nTime, nConditions, nParticipants);
acceleration = nan(nTime, nConditions, nParticipants);
cumulativePathLength = nan(nTime, nConditions, nParticipants);
baselineDisplacement = nan(nTime, nConditions, nParticipants);
dispersion = nan(nTime, nConditions, nParticipants);
totalPathLength = nan(nConditions, nParticipants);

deltaTime = diff(time);
velocityTimeStep = (deltaTime(1:end-1) + deltaTime(2:end)) / 2;
baselineMask = define_baseline_mask(time, opts.baseline);

for part = 1:nParticipants
    if ismember(part, participantsIncluded)
        otherParticipants = setdiff(participantsIncluded, part);
    else
        otherParticipants = participantsIncluded;
    end
    if ~isempty(otherParticipants)
        pooledCentroid = mean(mean(trajectories(:,:,:,otherParticipants), 4, 'omitnan'), 3, 'omitnan');
    else
        pooledCentroid = mean(trajectories(:,:,:,part), 3, 'omitnan');
    end

    for cond = 1:nConditions
        trajectory = trajectories(:,:,cond,part);
        stepVectors = diff(trajectory, 1, 1);
        stepDistances = sqrt(sum(stepVectors.^2, 2));

        velocity(2:end,:,cond,part) = stepVectors ./ deltaTime;
        speed(2:end,cond,part) = sqrt(sum(velocity(2:end,:,cond,part).^2, 2));

        accelerationVector(3:end,:,cond,part) = ...
            diff(velocity(2:end,:,cond,part), 1, 1) ./ velocityTimeStep;
        acceleration(3:end,cond,part) = ...
            sqrt(sum(accelerationVector(3:end,:,cond,part).^2, 2));

        cumulativePathLength(:,cond,part) = [0; cumsum(stepDistances)];
        totalPathLength(cond,part) = sum(stepDistances, 'omitnan');

        baselineCentroid = mean(trajectory(baselineMask,:), 1, 'omitnan');
        baselineDisplacement(:,cond,part) = ...
            sqrt(sum((trajectory - baselineCentroid).^2, 2));
        dispersion(:,cond,part) = ...
            sqrt(sum((trajectory - pooledCentroid).^2, 2));
    end
end

centroidComparisons = build_centroid_distance_outputs( ...
    meanCoordinates, time, conditionNames);

PHASE_STATS = struct();
PHASE_STATS.Time = time;
PHASE_STATS.PCs = PCs;
PHASE_STATS.Trajectories = trajectories;
PHASE_STATS.Metrics.Velocity = velocity;
PHASE_STATS.Metrics.Speed = speed;
PHASE_STATS.Metrics.AccelerationVector = accelerationVector;
PHASE_STATS.Metrics.Acceleration = acceleration;
PHASE_STATS.Metrics.Dispersion = dispersion;
PHASE_STATS.Metrics.BaselineDisplacement = baselineDisplacement;
PHASE_STATS.Metrics.CumulativePathLength = cumulativePathLength;
PHASE_STATS.Metrics.TotalPathLength = totalPathLength;
PHASE_STATS.Descriptive.ConditionMeanCoordinates = meanCoordinates;
PHASE_STATS.Descriptive.CentroidComparisons = centroidComparisons;

PHASE_STATS.Settings.ConditionIndices = conditionIndices;
PHASE_STATS.Settings.ConditionNames = conditionNames;
PHASE_STATS.Settings.GroupMembers = groupMembers;
PHASE_STATS.Settings.GroupNames = groupNames;
PHASE_STATS.Settings.GroupLabels = groupLabels;
PHASE_STATS.Settings.Baseline = [time(find(baselineMask,1,'first')) ...
                                time(find(baselineMask,1,'last'))];
PHASE_STATS.Settings.SmoothingSamples = opts.smoothingsamples;
PHASE_STATS.Settings.Alpha = opts.alpha;
PHASE_STATS.Settings.FDR = lower(char(opts.fdr));
PHASE_STATS.Settings.FDRFamily = ...
    'Each phase-space or scalar-metric comparison category across its time points and pairwise comparisons';
PHASE_STATS.Settings.TestType = testType;

%% --------------------------- Run statistics ----------------------------

if strcmpi(opts.statistics, 'off')
    PHASE_STATS.Tests = struct('Enabled', false, ...
        'Reason', 'Statistics were disabled by the user.');
    return
end

if length(participantsIncluded) < 2
    warning('At least two participants are required for statistical testing. Metrics were computed without inferential tests.');
    PHASE_STATS.Tests = struct('Enabled', false, ...
        'Reason', 'At least two participants are required for inferential statistics.');
    return
end

disp('Computing phase-space statistics')

PHASE_STATS.Tests.Enabled = true;
PHASE_STATS.Tests.PhaseSpace = run_phase_space_tests( ...
    trajectories, time, conditionNames, groupMembers, groupNames, opts);

metricNames = normalize_metric_names(opts.testmetrics);
for metricIndex = 1:length(metricNames)
    metricName = metricNames{metricIndex};
    if strcmp(metricName, 'TotalPathLength')
        metricData = reshape(totalPathLength, 1, nConditions, nParticipants);
        metricTime = time(end);
    else
        metricData = PHASE_STATS.Metrics.(metricName);
        metricTime = time;
    end

    PHASE_STATS.Tests.Metrics.(metricName) = run_scalar_metric_tests( ...
        metricData, metricTime, conditionNames, ...
        groupMembers, groupNames, groupLabels, testType, opts);
end

end

%% ----------------------------- Helpers ---------------------------------

function baselineMask = define_baseline_mask(time, baseline)
if isempty(baseline)
    baselineMask = time <= 0;
    if ~any(baselineMask)
        baselineMask = false(size(time));
        baselineMask(1) = true;
    end
else
    if ~isnumeric(baseline) || numel(baseline) ~= 2 || any(~isfinite(baseline))
        error('"baseline" must be empty or a finite [start end] vector in seconds.');
    end
    baseline = sort(baseline(:));
    baselineMask = time >= baseline(1) & time <= baseline(2);
    if ~any(baselineMask)
        error('The requested baseline does not contain any available time samples.');
    end
end
end

function outputs = build_centroid_distance_outputs(meanCoordinates, time, conditionNames)
nConditions = size(meanCoordinates,3);
outputs = {};
counter = 0;
for cond1 = 1:nConditions-1
    for cond2 = cond1+1:nConditions
        counter = counter + 1;
        difference = meanCoordinates(:,:,cond1) - meanCoordinates(:,:,cond2);
        outputs{counter} = struct( ...
            'Label', [conditionNames{cond1} '_vs_' conditionNames{cond2}], ...
            'Condition1', conditionNames{cond1}, ...
            'Condition2', conditionNames{cond2}, ...
            'Time', time, ...
            'SignedComponentDifference', difference, ...
            'EuclideanDistance', sqrt(sum(difference.^2, 2))); %#ok<AGROW>
    end
end
end

function metricNames = normalize_metric_names(metricInput)
validNames = {'Dispersion','Speed','Acceleration','BaselineDisplacement', ...
              'CumulativePathLength','TotalPathLength'};
if ischar(metricInput) || isstring(metricInput)
    metricNames = cellstr(metricInput);
elseif iscell(metricInput)
    metricNames = metricInput;
else
    error('"testmetrics" must be a character vector, string array, or cell array.');
end

for metricIndex = 1:length(metricNames)
    match = find(strcmpi(metricNames{metricIndex}, validNames), 1);
    if isempty(match)
        error(['Unknown metric requested in "testmetrics": ' char(metricNames{metricIndex})]);
    end
    metricNames{metricIndex} = validNames{match};
end
metricNames = unique(metricNames, 'stable');
end

function names = normalize_names(inputNames, nNames, prefix)
if isempty(inputNames)
    names = arrayfun(@(index) [prefix num2str(index)], ...
        1:nNames, 'UniformOutput', false);
else
    names = cellstr(string(inputNames));
    if length(names) ~= nNames
        error(['The number of names supplied for ' lower(prefix) 's does not match the selected data.']);
    end
end
end

function [members, names, labels] = normalize_groups(groupIndices, groupNames, nParticipants)
labels = nan(nParticipants,1);

if isempty(groupIndices)
    members = {1:nParticipants};
elseif iscell(groupIndices)
    members = groupIndices(:)';
    participantsUsed = [];
    for group = 1:length(members)
        indices = members{group};
        if ~isnumeric(indices) || isempty(indices) || any(~isfinite(indices)) || ...
                any(indices < 1) || any(indices > nParticipants) || ...
                any(fix(indices) ~= indices)
            error('Each cell in "groupindices" must contain valid participant indices.');
        end
        indices = unique(indices(:)', 'stable');
        if any(ismember(indices, participantsUsed))
            error('A participant cannot occur in more than one group.');
        end
        participantsUsed = [participantsUsed indices]; %#ok<AGROW>
        members{group} = indices;
    end
elseif isnumeric(groupIndices) && isvector(groupIndices) && ...
        length(groupIndices) == nParticipants
    inputLabels = groupIndices(:);
    levels = unique(inputLabels(isfinite(inputLabels)), 'stable');
    members = cell(1,length(levels));
    for group = 1:length(levels)
        members{group} = find(inputLabels == levels(group))';
    end
else
    error(['"groupindices" must be a cell array of participant-index vectors ' ...
           'or one numeric group label per participant.']);
end

if isempty(groupNames)
    if length(members) == 1
        names = {'AllParticipants'};
    else
        names = arrayfun(@(index) ['Group' num2str(index)], ...
            1:length(members), 'UniformOutput', false);
    end
else
    names = cellstr(string(groupNames));
    if length(names) ~= length(members)
        error('"groupnames" must contain one label per group.');
    end
end

for group = 1:length(members)
    labels(members{group}) = group;
end
end

function validate_on_off(value, name)
if ~(ischar(value) || (isstring(value) && isscalar(value))) || ...
        ~any(strcmpi(char(value), {'on','off'}))
    error(['"' name '" must be ''on'' or ''off''.']);
end
end

function opts = parse_name_value_pairs(opts, varargin)
if mod(length(varargin), 2) ~= 0
    error('Arguments must be given as name-value pairs.');
end
for inputIndex = 1:2:length(varargin)
    name = lower(varargin{inputIndex});
    if isfield(opts, name)
        opts.(name) = varargin{inputIndex+1};
    else
        error(['Unrecognized argument: ' name]);
    end
end
end

%% ---------------------- Phase-space statistical tests ------------------

function results = run_phase_space_tests(trajectories, time, conditionNames, ...
    groupMembers, groupNames, opts)

results.ConditionComparisons = {};
results.GroupComparisons = {};
results.Interactions = {};

if strcmpi(opts.pairwise, 'off')
    return
end

nConditions = size(trajectories,3);
nGroups = length(groupMembers);
allParticipants = unique([groupMembers{:}], 'stable');

% Condition comparisons use paired observations. When several groups are
% supplied, results are provided both across all participants and within
% each group.
conditionContexts = groupMembers;
conditionContextNames = groupNames;
if nGroups > 1
    conditionContexts = [{allParticipants} groupMembers];
    conditionContextNames = [{'AllParticipants'} groupNames];
end

counter = 0;
for context = 1:length(conditionContexts)
    participants = conditionContexts{context};
    for cond1 = 1:nConditions-1
        for cond2 = cond1+1:nConditions
            A = extract_trajectory_data(trajectories, cond1, participants);
            B = extract_trajectory_data(trajectories, cond2, participants);
            test = paired_hotelling_timecourse(A, B, opts);

            counter = counter + 1;
            results.ConditionComparisons{counter} = package_hotelling_test( ...
                'conditions', conditionNames{cond1}, conditionNames{cond2}, ...
                conditionContextNames{context}, time, A, B, test);
        end
    end
end

% Group comparisons are independent and are calculated within condition.
counter = 0;
for cond = 1:nConditions
    for group1 = 1:nGroups-1
        for group2 = group1+1:nGroups
            A = extract_trajectory_data(trajectories, cond, groupMembers{group1});
            B = extract_trajectory_data(trajectories, cond, groupMembers{group2});
            test = independent_hotelling_timecourse(A, B, opts);

            counter = counter + 1;
            results.GroupComparisons{counter} = package_hotelling_test( ...
                'groups', groupNames{group1}, groupNames{group2}, ...
                conditionNames{cond}, time, A, B, test);
        end
    end
end

% A pairwise interaction compares condition-difference vectors between
% independent groups.
counter = 0;
for group1 = 1:nGroups-1
    for group2 = group1+1:nGroups
        for cond1 = 1:nConditions-1
            for cond2 = cond1+1:nConditions
                A1 = extract_trajectory_data(trajectories, cond1, groupMembers{group1});
                A2 = extract_trajectory_data(trajectories, cond2, groupMembers{group1});
                B1 = extract_trajectory_data(trajectories, cond1, groupMembers{group2});
                B2 = extract_trajectory_data(trajectories, cond2, groupMembers{group2});
                differenceA = A1 - A2;
                differenceB = B1 - B2;
                test = independent_hotelling_timecourse(differenceA, differenceB, opts);

                counter = counter + 1;
                contextLabel = [conditionNames{cond1} '_minus_' conditionNames{cond2}];
                results.Interactions{counter} = package_hotelling_test( ...
                    'interaction', groupNames{group1}, groupNames{group2}, ...
                    contextLabel, time, differenceA, differenceB, test);
            end
        end
    end
end

results.ConditionComparisons = apply_hotelling_fdr_family( ...
    results.ConditionComparisons, opts);
results.GroupComparisons = apply_hotelling_fdr_family( ...
    results.GroupComparisons, opts);
results.Interactions = apply_hotelling_fdr_family( ...
    results.Interactions, opts);
end

function data = extract_trajectory_data(trajectories, condition, participants)
data = trajectories(:,:,condition,participants);
data = reshape(data, size(trajectories,1), size(trajectories,2), length(participants));
end

function test = paired_hotelling_timecourse(A, B, opts)
nTime = size(A,1);
nDimensions = size(A,2);
test.T2 = nan(nTime,1);
test.F = nan(nTime,1);
test.DF1 = nan(nTime,1);
test.DF2 = nan(nTime,1);
test.P = nan(nTime,1);
test.EffectiveDimensions = nan(nTime,1);

for timeIndex = 1:nTime
    difference = squeeze(A(timeIndex,:,:)-B(timeIndex,:,:))';
    if nDimensions == 1
        difference = difference(:);
    end
    difference = difference(all(isfinite(difference),2),:);
    nParticipants = size(difference,1);
    if nParticipants < 2
        continue
    end

    differenceMean = mean(difference,1);
    covarianceMatrix = cov(difference,0);
    [inverseCovariance, effectiveDimensions] = covariance_inverse(covarianceMatrix);
    if effectiveDimensions < 1 || nParticipants <= effectiveDimensions
        continue
    end

    T2 = nParticipants * differenceMean * inverseCovariance * differenceMean';
    F = (nParticipants-effectiveDimensions) * T2 / ...
        (effectiveDimensions*(nParticipants-1));

    test.T2(timeIndex) = T2;
    test.F(timeIndex) = F;
    test.DF1(timeIndex) = effectiveDimensions;
    test.DF2(timeIndex) = nParticipants-effectiveDimensions;
    test.P(timeIndex) = 1-fcdf(F, test.DF1(timeIndex), test.DF2(timeIndex));
    test.EffectiveDimensions(timeIndex) = effectiveDimensions;
end

test.P_FDR = adjust_pvalues(test.P, opts);
test.Significant = test.P_FDR < opts.alpha;
end

function test = independent_hotelling_timecourse(A, B, opts)
nTime = size(A,1);
nDimensions = size(A,2);
test.T2 = nan(nTime,1);
test.F = nan(nTime,1);
test.DF1 = nan(nTime,1);
test.DF2 = nan(nTime,1);
test.P = nan(nTime,1);
test.EffectiveDimensions = nan(nTime,1);

for timeIndex = 1:nTime
    dataA = squeeze(A(timeIndex,:,:))';
    dataB = squeeze(B(timeIndex,:,:))';
    if nDimensions == 1
        dataA = dataA(:);
        dataB = dataB(:);
    end
    dataA = dataA(all(isfinite(dataA),2),:);
    dataB = dataB(all(isfinite(dataB),2),:);
    nA = size(dataA,1);
    nB = size(dataB,1);
    if nA < 2 || nB < 2
        continue
    end

    covarianceA = cov(dataA,0);
    covarianceB = cov(dataB,0);
    pooledCovariance = ((nA-1)*covarianceA + (nB-1)*covarianceB) / (nA+nB-2);
    [inverseCovariance, effectiveDimensions] = covariance_inverse(pooledCovariance);
    denominatorDF = nA+nB-effectiveDimensions-1;
    if effectiveDimensions < 1 || denominatorDF < 1
        continue
    end

    meanDifference = mean(dataA,1)-mean(dataB,1);
    T2 = (nA*nB/(nA+nB)) * meanDifference * inverseCovariance * meanDifference';
    F = denominatorDF * T2 / (effectiveDimensions*(nA+nB-2));

    test.T2(timeIndex) = T2;
    test.F(timeIndex) = F;
    test.DF1(timeIndex) = effectiveDimensions;
    test.DF2(timeIndex) = denominatorDF;
    test.P(timeIndex) = 1-fcdf(F, test.DF1(timeIndex), test.DF2(timeIndex));
    test.EffectiveDimensions(timeIndex) = effectiveDimensions;
end

test.P_FDR = adjust_pvalues(test.P, opts);
test.Significant = test.P_FDR < opts.alpha;
end

function [inverseCovariance, effectiveDimensions] = covariance_inverse(covarianceMatrix)
if isscalar(covarianceMatrix)
    if isfinite(covarianceMatrix) && covarianceMatrix > 0
        inverseCovariance = 1/covarianceMatrix;
        effectiveDimensions = 1;
    else
        inverseCovariance = NaN;
        effectiveDimensions = 0;
    end
    return
end

if any(~isfinite(covarianceMatrix(:)))
    inverseCovariance = nan(size(covarianceMatrix));
    effectiveDimensions = 0;
    return
end

effectiveDimensions = rank(covarianceMatrix);
inverseCovariance = pinv(covarianceMatrix);
end

function comparison = package_hotelling_test(comparisonType, level1, level2, ...
    context, time, A, B, test)

meanA = mean(A,3,'omitnan');
meanB = mean(B,3,'omitnan');
signedDifference = meanA-meanB;

comparison.Label = [level1 '_vs_' level2 '__' context];
comparison.Comparison = comparisonType;
comparison.Level1 = level1;
comparison.Level2 = level2;
comparison.Context = context;
comparison.Time = time;
comparison.Level1MeanCoordinates = meanA;
comparison.Level2MeanCoordinates = meanB;
comparison.SignedComponentDifference = signedDifference;
comparison.EuclideanDistance = sqrt(sum(signedDifference.^2,2));
comparison.Hotelling = test;
end

function comparisons = apply_hotelling_fdr_family(comparisons, opts)
if isempty(comparisons)
    return
end

allP = [];
lengths = zeros(length(comparisons),1);
for comparisonIndex = 1:length(comparisons)
    currentP = comparisons{comparisonIndex}.Hotelling.P;
    lengths(comparisonIndex) = numel(currentP);
    allP = [allP; currentP(:)]; %#ok<AGROW>
end

allAdjusted = adjust_pvalues(allP, opts);
startIndex = 1;
for comparisonIndex = 1:length(comparisons)
    indices = startIndex:startIndex+lengths(comparisonIndex)-1;
    comparisons{comparisonIndex}.Hotelling.P_FDR = allAdjusted(indices);
    comparisons{comparisonIndex}.Hotelling.Significant = ...
        allAdjusted(indices) < opts.alpha;
    startIndex = indices(end)+1;
end
end

%% ----------------------- Scalar-metric statistics ----------------------

function results = run_scalar_metric_tests(metricData, time, conditionNames, ...
    groupMembers, groupNames, groupLabels, testType, opts)

results.ConditionComparisons = {};
results.GroupComparisons = {};
results.Interactions = {};
results.Omnibus = struct();

nConditions = size(metricData,2);
nGroups = length(groupMembers);
allParticipants = unique([groupMembers{:}], 'stable');

if strcmpi(opts.pairwise, 'on')
    conditionContexts = groupMembers;
    conditionContextNames = groupNames;
    if nGroups > 1
        conditionContexts = [{allParticipants} groupMembers];
        conditionContextNames = [{'AllParticipants'} groupNames];
    end

    counter = 0;
    for context = 1:length(conditionContexts)
        participants = conditionContexts{context};
        for cond1 = 1:nConditions-1
            for cond2 = cond1+1:nConditions
                A = extract_metric_data(metricData, cond1, participants);
                B = extract_metric_data(metricData, cond2, participants);
                counter = counter + 1;
                results.ConditionComparisons{counter} = scalar_paired_comparison( ...
                    A, B, time, conditionNames{cond1}, conditionNames{cond2}, ...
                    conditionContextNames{context}, 'conditions', testType);
            end
        end
    end

    counter = 0;
    for cond = 1:nConditions
        for group1 = 1:nGroups-1
            for group2 = group1+1:nGroups
                A = extract_metric_data(metricData, cond, groupMembers{group1});
                B = extract_metric_data(metricData, cond, groupMembers{group2});
                counter = counter + 1;
                results.GroupComparisons{counter} = scalar_independent_comparison( ...
                    A, B, time, groupNames{group1}, groupNames{group2}, ...
                    conditionNames{cond}, 'groups', testType);
            end
        end
    end

    counter = 0;
    for group1 = 1:nGroups-1
        for group2 = group1+1:nGroups
            for cond1 = 1:nConditions-1
                for cond2 = cond1+1:nConditions
                    A1 = extract_metric_data(metricData, cond1, groupMembers{group1});
                    A2 = extract_metric_data(metricData, cond2, groupMembers{group1});
                    B1 = extract_metric_data(metricData, cond1, groupMembers{group2});
                    B2 = extract_metric_data(metricData, cond2, groupMembers{group2});
                    contextLabel = [conditionNames{cond1} '_minus_' conditionNames{cond2}];
                    counter = counter + 1;
                    results.Interactions{counter} = scalar_independent_comparison( ...
                        A1-A2, B1-B2, time, groupNames{group1}, groupNames{group2}, ...
                        contextLabel, 'interaction', testType);
                end
            end
        end
    end

    results.ConditionComparisons = apply_scalar_fdr_family( ...
        results.ConditionComparisons, testType, opts);
    results.GroupComparisons = apply_scalar_fdr_family( ...
        results.GroupComparisons, testType, opts);
    results.Interactions = apply_scalar_fdr_family( ...
        results.Interactions, testType, opts);
end

if strcmpi(opts.omnibus, 'on')
    results.Omnibus.Parametric = mixed_anova_timecourse( ...
        metricData, time, groupLabels, opts);
end
end

function data = extract_metric_data(metricData, condition, participants)
data = metricData(:,condition,participants);
data = reshape(data, size(metricData,1), length(participants));
end

function comparison = scalar_paired_comparison(A, B, time, level1, level2, ...
    context, comparisonType, testType)

nTime = size(A,1);
comparison = package_scalar_comparison(A, B, time, level1, level2, ...
    context, comparisonType);

if any(strcmp(testType, {'parametric','both'}))
    result = initialize_scalar_test(nTime);
    for timeIndex = 1:nTime
        valid = isfinite(A(timeIndex,:)) & isfinite(B(timeIndex,:));
        valuesA = A(timeIndex,valid);
        valuesB = B(timeIndex,valid);
        result.N1(timeIndex) = length(valuesA);
        result.N2(timeIndex) = length(valuesB);
        if length(valuesA) < 2
            continue
        end
        [~, result.P(timeIndex), ~, statistics] = ttest(valuesA, valuesB);
        result.Statistic(timeIndex) = statistics.tstat;
        result.DF(timeIndex) = statistics.df;
    end
    comparison.Parametric = result;
end

if any(strcmp(testType, {'nonparametric','both'}))
    result = initialize_scalar_test(nTime);
    for timeIndex = 1:nTime
        valid = isfinite(A(timeIndex,:)) & isfinite(B(timeIndex,:));
        valuesA = A(timeIndex,valid);
        valuesB = B(timeIndex,valid);
        result.N1(timeIndex) = length(valuesA);
        result.N2(timeIndex) = length(valuesB);
        if length(valuesA) < 2 || all(valuesA == valuesB)
            if length(valuesA) >= 2 && all(valuesA == valuesB)
                result.P(timeIndex) = 1;
                result.Statistic(timeIndex) = 0;
            end
            continue
        end
        try
            [result.P(timeIndex), ~, statistics] = signrank(valuesA, valuesB);
            if isfield(statistics, 'zval')
                result.Statistic(timeIndex) = statistics.zval;
            elseif isfield(statistics, 'signedrank')
                result.Statistic(timeIndex) = statistics.signedrank;
            end
        catch
            result.P(timeIndex) = NaN;
        end
    end
    comparison.Nonparametric = result;
end
end

function comparison = scalar_independent_comparison(A, B, time, level1, level2, ...
    context, comparisonType, testType)

nTime = size(A,1);
comparison = package_scalar_comparison(A, B, time, level1, level2, ...
    context, comparisonType);

if any(strcmp(testType, {'parametric','both'}))
    result = initialize_scalar_test(nTime);
    for timeIndex = 1:nTime
        valuesA = A(timeIndex,isfinite(A(timeIndex,:)));
        valuesB = B(timeIndex,isfinite(B(timeIndex,:)));
        result.N1(timeIndex) = length(valuesA);
        result.N2(timeIndex) = length(valuesB);
        if length(valuesA) < 2 || length(valuesB) < 2
            continue
        end
        [~, result.P(timeIndex), ~, statistics] = ...
            ttest2(valuesA, valuesB, 'Vartype', 'unequal');
        result.Statistic(timeIndex) = statistics.tstat;
        result.DF(timeIndex) = statistics.df;
    end
    comparison.Parametric = result;
end

if any(strcmp(testType, {'nonparametric','both'}))
    result = initialize_scalar_test(nTime);
    for timeIndex = 1:nTime
        valuesA = A(timeIndex,isfinite(A(timeIndex,:)));
        valuesB = B(timeIndex,isfinite(B(timeIndex,:)));
        result.N1(timeIndex) = length(valuesA);
        result.N2(timeIndex) = length(valuesB);
        if isempty(valuesA) || isempty(valuesB)
            continue
        end
        try
            [result.P(timeIndex), ~, statistics] = ranksum(valuesA, valuesB);
            if isfield(statistics, 'zval')
                result.Statistic(timeIndex) = statistics.zval;
            elseif isfield(statistics, 'ranksum')
                result.Statistic(timeIndex) = statistics.ranksum;
            end
        catch
            result.P(timeIndex) = NaN;
        end
    end
    comparison.Nonparametric = result;
end
end

function comparison = package_scalar_comparison(A, B, time, level1, level2, ...
    context, comparisonType)

comparison.Label = [level1 '_vs_' level2 '__' context];
comparison.Comparison = comparisonType;
comparison.Level1 = level1;
comparison.Level2 = level2;
comparison.Context = context;
comparison.Time = time;
comparison.Level1Mean = mean(A,2,'omitnan');
comparison.Level2Mean = mean(B,2,'omitnan');
comparison.MeanDifference = comparison.Level1Mean-comparison.Level2Mean;
end

function result = initialize_scalar_test(nTime)
result.Statistic = nan(nTime,1);
result.DF = nan(nTime,1);
result.P = nan(nTime,1);
result.P_FDR = nan(nTime,1);
result.Significant = false(nTime,1);
result.N1 = nan(nTime,1);
result.N2 = nan(nTime,1);
end

function comparisons = apply_scalar_fdr_family(comparisons, testType, opts)
if isempty(comparisons)
    return
end

if any(strcmp(testType, {'parametric','both'}))
    comparisons = apply_scalar_fdr_field(comparisons, 'Parametric', opts);
end
if any(strcmp(testType, {'nonparametric','both'}))
    comparisons = apply_scalar_fdr_field(comparisons, 'Nonparametric', opts);
end
end

function comparisons = apply_scalar_fdr_field(comparisons, fieldName, opts)
allP = [];
lengths = zeros(length(comparisons),1);
for comparisonIndex = 1:length(comparisons)
    currentP = comparisons{comparisonIndex}.(fieldName).P;
    lengths(comparisonIndex) = numel(currentP);
    allP = [allP; currentP(:)]; %#ok<AGROW>
end

allAdjusted = adjust_pvalues(allP, opts);
startIndex = 1;
for comparisonIndex = 1:length(comparisons)
    indices = startIndex:startIndex+lengths(comparisonIndex)-1;
    comparisons{comparisonIndex}.(fieldName).P_FDR = allAdjusted(indices);
    comparisons{comparisonIndex}.(fieldName).Significant = ...
        allAdjusted(indices) < opts.alpha;
    startIndex = indices(end)+1;
end
end

%% ------------------------ Repeated/mixed ANOVA --------------------------

function omnibus = mixed_anova_timecourse(metricData, time, groupLabels, opts)
nTime = size(metricData,1);
nConditions = size(metricData,2);

omnibus.Time = time;
omnibus.Condition = initialize_anova_effect(nTime);
omnibus.Group = initialize_anova_effect(nTime);
omnibus.Interaction = initialize_anova_effect(nTime);

for timeIndex = 1:nTime
    values = reshape(metricData(timeIndex,:,:), nConditions, size(metricData,3))';
    valid = all(isfinite(values),2) & isfinite(groupLabels);
    values = values(valid,:);
    labels = groupLabels(valid);
    if isempty(values)
        continue
    end

    effects = calculate_mixed_anova(values, labels);
    effectNames = {'Condition','Group','Interaction'};
    for effectIndex = 1:length(effectNames)
        effectName = effectNames{effectIndex};
        omnibus.(effectName).F(timeIndex) = effects.(effectName).F;
        omnibus.(effectName).DF1(timeIndex) = effects.(effectName).DF1;
        omnibus.(effectName).DF2(timeIndex) = effects.(effectName).DF2;
        omnibus.(effectName).P(timeIndex) = effects.(effectName).P;
        omnibus.(effectName).EpsilonGG(timeIndex) = effects.(effectName).EpsilonGG;
        omnibus.(effectName).DF1_GG(timeIndex) = effects.(effectName).DF1_GG;
        omnibus.(effectName).DF2_GG(timeIndex) = effects.(effectName).DF2_GG;
        omnibus.(effectName).P_GG(timeIndex) = effects.(effectName).P_GG;
    end
end

effectNames = {'Condition','Group','Interaction'};
for effectIndex = 1:length(effectNames)
    effectName = effectNames{effectIndex};
    omnibus.(effectName).P_FDR = adjust_pvalues(omnibus.(effectName).P_GG, opts);
    omnibus.(effectName).Significant = ...
        omnibus.(effectName).P_FDR < opts.alpha;
end
end

function effect = initialize_anova_effect(nTime)
effect.F = nan(nTime,1);
effect.DF1 = nan(nTime,1);
effect.DF2 = nan(nTime,1);
effect.P = nan(nTime,1);
effect.EpsilonGG = nan(nTime,1);
effect.DF1_GG = nan(nTime,1);
effect.DF2_GG = nan(nTime,1);
effect.P_GG = nan(nTime,1);
effect.P_FDR = nan(nTime,1);
effect.Significant = false(nTime,1);
end

function effects = calculate_mixed_anova(values, groupLabels)
effects.Condition = empty_anova_value();
effects.Group = empty_anova_value();
effects.Interaction = empty_anova_value();

nParticipants = size(values,1);
nConditions = size(values,2);
groupLevels = unique(groupLabels, 'stable');
nGroups = length(groupLevels);

if nParticipants < 2
    return
end

grandMean = mean(values(:));
participantMeans = mean(values,2);
conditionMeans = mean(values,1);

if nConditions > 1
    conditionSS = nParticipants * sum((conditionMeans-grandMean).^2);
else
    conditionSS = 0;
end

if nGroups == 1
    if nConditions < 2
        return
    end
    errorValues = values-participantMeans-conditionMeans+grandMean;
    errorSS = sum(errorValues(:).^2);
    conditionDF = nConditions-1;
    errorDF = (nParticipants-1)*(nConditions-1);
    effects.Condition = make_anova_value(conditionSS, conditionDF, errorSS, errorDF);
    epsilonGG = greenhouse_geisser_epsilon(values, groupLabels);
    effects.Condition = apply_greenhouse_geisser(effects.Condition, epsilonGG);
    return
end

groupMeans = nan(nGroups,1);
groupConditionMeans = nan(nGroups,nConditions);
groupSizes = nan(nGroups,1);
subjectWithinGroupSS = 0;

for group = 1:nGroups
    groupMask = groupLabels == groupLevels(group);
    groupSizes(group) = sum(groupMask);
    groupMeans(group) = mean(values(groupMask,:), 'all');
    groupConditionMeans(group,:) = mean(values(groupMask,:),1);
    subjectWithinGroupSS = subjectWithinGroupSS + ...
        nConditions*sum((participantMeans(groupMask)-groupMeans(group)).^2);
end

groupSS = nConditions * sum(groupSizes.*(groupMeans-grandMean).^2);
interactionSS = 0;
errorSS = 0;
for group = 1:nGroups
    groupMask = groupLabels == groupLevels(group);
    interactionTerms = groupConditionMeans(group,:)-groupMeans(group)-conditionMeans+grandMean;
    interactionSS = interactionSS + groupSizes(group)*sum(interactionTerms.^2);

    groupValues = values(groupMask,:);
    groupParticipantMeans = participantMeans(groupMask);
    residuals = groupValues-groupParticipantMeans-groupConditionMeans(group,:)+groupMeans(group);
    errorSS = errorSS+sum(residuals(:).^2);
end

groupDF = nGroups-1;
subjectWithinGroupDF = nParticipants-nGroups;
effects.Group = make_anova_value(groupSS, groupDF, ...
    subjectWithinGroupSS, subjectWithinGroupDF);

if nConditions > 1
    conditionDF = nConditions-1;
    interactionDF = (nGroups-1)*(nConditions-1);
    errorDF = (nParticipants-nGroups)*(nConditions-1);
    effects.Condition = make_anova_value(conditionSS, conditionDF, errorSS, errorDF);
    effects.Interaction = make_anova_value(interactionSS, interactionDF, errorSS, errorDF);
    epsilonGG = greenhouse_geisser_epsilon(values, groupLabels);
    effects.Condition = apply_greenhouse_geisser(effects.Condition, epsilonGG);
    effects.Interaction = apply_greenhouse_geisser(effects.Interaction, epsilonGG);
end
end

function effect = empty_anova_value()
effect = struct('F',NaN,'DF1',NaN,'DF2',NaN,'P',NaN, ...
    'EpsilonGG',NaN,'DF1_GG',NaN,'DF2_GG',NaN,'P_GG',NaN);
end

function effect = make_anova_value(effectSS, effectDF, errorSS, errorDF)
effect = empty_anova_value();
if effectDF < 1 || errorDF < 1 || errorSS < 0
    return
end

effectMeanSquare = effectSS/effectDF;
errorMeanSquare = errorSS/errorDF;
if errorMeanSquare == 0
    if effectMeanSquare == 0
        F = 0;
        P = 1;
    else
        F = Inf;
        P = 0;
    end
else
    F = effectMeanSquare/errorMeanSquare;
    P = 1-fcdf(F,effectDF,errorDF);
end

effect.F = F;
effect.DF1 = effectDF;
effect.DF2 = errorDF;
effect.P = P;
effect.EpsilonGG = 1;
effect.DF1_GG = effectDF;
effect.DF2_GG = errorDF;
effect.P_GG = P;
end

function epsilonGG = greenhouse_geisser_epsilon(values, groupLabels)
nConditions = size(values,2);
if nConditions <= 2
    epsilonGG = 1;
    return
end

groupLevels = unique(groupLabels, 'stable');
residualValues = values;
for group = 1:length(groupLevels)
    groupMask = groupLabels == groupLevels(group);
    residualValues(groupMask,:) = values(groupMask,:) - mean(values(groupMask,:),1);
end

covarianceMatrix = cov(residualValues);
centeringMatrix = eye(nConditions)-ones(nConditions)/nConditions;
centeredCovariance = centeringMatrix*covarianceMatrix*centeringMatrix;
denominator = (nConditions-1)*trace(centeredCovariance*centeredCovariance);
if denominator <= 0 || ~isfinite(denominator)
    epsilonGG = 1;
else
    epsilonGG = trace(centeredCovariance)^2/denominator;
    epsilonGG = min(1,max(1/(nConditions-1),epsilonGG));
end
end

function effect = apply_greenhouse_geisser(effect, epsilonGG)
if ~isfinite(effect.F) || ~isfinite(effect.DF1) || ~isfinite(effect.DF2)
    return
end

effect.EpsilonGG = epsilonGG;
effect.DF1_GG = effect.DF1*epsilonGG;
effect.DF2_GG = effect.DF2*epsilonGG;
effect.P_GG = 1-fcdf(effect.F,effect.DF1_GG,effect.DF2_GG);
end

%% ------------------------------ FDR ------------------------------------

function adjustedP = adjust_pvalues(pValues, opts)
if strcmpi(opts.fdr, 'off')
    adjustedP = pValues;
else
    adjustedP = benjamini_hochberg(pValues);
end
end

function adjustedP = benjamini_hochberg(pValues)
originalSize = size(pValues);
pValues = pValues(:);
adjustedP = nan(size(pValues));
validIndices = find(isfinite(pValues));
if isempty(validIndices)
    adjustedP = reshape(adjustedP, originalSize);
    return
end

[sortedP, sortOrder] = sort(pValues(validIndices));
nValid = length(sortedP);
adjustedSorted = sortedP.*nValid./(1:nValid)';
for index = nValid-1:-1:1
    adjustedSorted(index) = min(adjustedSorted(index), adjustedSorted(index+1));
end
adjustedSorted = min(adjustedSorted,1);

restored = nan(nValid,1);
restored(sortOrder) = adjustedSorted;
adjustedP(validIndices) = restored;
adjustedP = reshape(adjustedP, originalSize);
end
